#!/bin/sh

### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start aesdsocket daemon at boot time
# Description:       Enable aesdsocket service provided by daemon.
### END INIT INFO

case "$1" in
  start)
    echo "Starting aesdsocket"
    start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
    ;;
  stop)
    echo "Stopping aesdsocket"
    start-stop-daemon -K  -n aesdsocket
    ;;
  restart)
    echo "Restarting aesdsocket"
    start-stop-daemon -K -n aesdsocket
    start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
    ;;
  force-reload)
    ;;
  status)
    echo -n "Status of aesdsocket "
    start-stop-daemon -T -n aesdsocket
    if [ "$?" -eq 0 ]; then
	echo "running"
    else
	echo "stopped"
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit 0
